// Generated by gencpp from file imu_driver/convert_to_quaternion_srvResponse.msg
// DO NOT EDIT!


#ifndef IMU_DRIVER_MESSAGE_CONVERT_TO_QUATERNION_SRVRESPONSE_H
#define IMU_DRIVER_MESSAGE_CONVERT_TO_QUATERNION_SRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_driver
{
template <class ContainerAllocator>
struct convert_to_quaternion_srvResponse_
{
  typedef convert_to_quaternion_srvResponse_<ContainerAllocator> Type;

  convert_to_quaternion_srvResponse_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , w(0.0)  {
    }
  convert_to_quaternion_srvResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct convert_to_quaternion_srvResponse_

typedef ::imu_driver::convert_to_quaternion_srvResponse_<std::allocator<void> > convert_to_quaternion_srvResponse;

typedef boost::shared_ptr< ::imu_driver::convert_to_quaternion_srvResponse > convert_to_quaternion_srvResponsePtr;
typedef boost::shared_ptr< ::imu_driver::convert_to_quaternion_srvResponse const> convert_to_quaternion_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator1> & lhs, const ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator1> & lhs, const ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imu_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a779879fadf0160734f906b8c19c7004";
  }

  static const char* value(const ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa779879fadf01607ULL;
  static const uint64_t static_value2 = 0x34f906b8c19c7004ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_driver/convert_to_quaternion_srvResponse";
  }

  static const char* value(const ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
;
  }

  static const char* value(const ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct convert_to_quaternion_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_driver::convert_to_quaternion_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_DRIVER_MESSAGE_CONVERT_TO_QUATERNION_SRVRESPONSE_H
