// Generated by gencpp from file imu_driver/convert_to_quaternion_srv.msg
// DO NOT EDIT!


#ifndef IMU_DRIVER_MESSAGE_CONVERT_TO_QUATERNION_SRV_H
#define IMU_DRIVER_MESSAGE_CONVERT_TO_QUATERNION_SRV_H

#include <ros/service_traits.h>


#include <imu_driver/convert_to_quaternion_srvRequest.h>
#include <imu_driver/convert_to_quaternion_srvResponse.h>


namespace imu_driver
{

struct convert_to_quaternion_srv
{

typedef convert_to_quaternion_srvRequest Request;
typedef convert_to_quaternion_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct convert_to_quaternion_srv
} // namespace imu_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::imu_driver::convert_to_quaternion_srv > {
  static const char* value()
  {
    return "b218cfe499191b24c074175e474522de";
  }

  static const char* value(const ::imu_driver::convert_to_quaternion_srv&) { return value(); }
};

template<>
struct DataType< ::imu_driver::convert_to_quaternion_srv > {
  static const char* value()
  {
    return "imu_driver/convert_to_quaternion_srv";
  }

  static const char* value(const ::imu_driver::convert_to_quaternion_srv&) { return value(); }
};


// service_traits::MD5Sum< ::imu_driver::convert_to_quaternion_srvRequest> should match
// service_traits::MD5Sum< ::imu_driver::convert_to_quaternion_srv >
template<>
struct MD5Sum< ::imu_driver::convert_to_quaternion_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::imu_driver::convert_to_quaternion_srv >::value();
  }
  static const char* value(const ::imu_driver::convert_to_quaternion_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::imu_driver::convert_to_quaternion_srvRequest> should match
// service_traits::DataType< ::imu_driver::convert_to_quaternion_srv >
template<>
struct DataType< ::imu_driver::convert_to_quaternion_srvRequest>
{
  static const char* value()
  {
    return DataType< ::imu_driver::convert_to_quaternion_srv >::value();
  }
  static const char* value(const ::imu_driver::convert_to_quaternion_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::imu_driver::convert_to_quaternion_srvResponse> should match
// service_traits::MD5Sum< ::imu_driver::convert_to_quaternion_srv >
template<>
struct MD5Sum< ::imu_driver::convert_to_quaternion_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::imu_driver::convert_to_quaternion_srv >::value();
  }
  static const char* value(const ::imu_driver::convert_to_quaternion_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::imu_driver::convert_to_quaternion_srvResponse> should match
// service_traits::DataType< ::imu_driver::convert_to_quaternion_srv >
template<>
struct DataType< ::imu_driver::convert_to_quaternion_srvResponse>
{
  static const char* value()
  {
    return DataType< ::imu_driver::convert_to_quaternion_srv >::value();
  }
  static const char* value(const ::imu_driver::convert_to_quaternion_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IMU_DRIVER_MESSAGE_CONVERT_TO_QUATERNION_SRV_H
