// Generated by gencpp from file imu_driver/imu_msg.msg
// DO NOT EDIT!


#ifndef IMU_DRIVER_MESSAGE_IMU_MSG_H
#define IMU_DRIVER_MESSAGE_IMU_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace imu_driver
{
template <class ContainerAllocator>
struct imu_msg_
{
  typedef imu_msg_<ContainerAllocator> Type;

  imu_msg_()
    : Header()
    , Latitude(0.0)
    , Longitude(0.0)
    , Altitude(0.0)
    , HDOP(0.0)
    , UTM_easting(0.0)
    , UTM_northing(0.0)
    , UTC(0.0)
    , Zone(0)
    , Letter()  {
    }
  imu_msg_(const ContainerAllocator& _alloc)
    : Header(_alloc)
    , Latitude(0.0)
    , Longitude(0.0)
    , Altitude(0.0)
    , HDOP(0.0)
    , UTM_easting(0.0)
    , UTM_northing(0.0)
    , UTC(0.0)
    , Zone(0)
    , Letter(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _Header_type;
  _Header_type Header;

   typedef double _Latitude_type;
  _Latitude_type Latitude;

   typedef double _Longitude_type;
  _Longitude_type Longitude;

   typedef double _Altitude_type;
  _Altitude_type Altitude;

   typedef double _HDOP_type;
  _HDOP_type HDOP;

   typedef double _UTM_easting_type;
  _UTM_easting_type UTM_easting;

   typedef double _UTM_northing_type;
  _UTM_northing_type UTM_northing;

   typedef double _UTC_type;
  _UTC_type UTC;

   typedef int64_t _Zone_type;
  _Zone_type Zone;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Letter_type;
  _Letter_type Letter;





  typedef boost::shared_ptr< ::imu_driver::imu_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_driver::imu_msg_<ContainerAllocator> const> ConstPtr;

}; // struct imu_msg_

typedef ::imu_driver::imu_msg_<std::allocator<void> > imu_msg;

typedef boost::shared_ptr< ::imu_driver::imu_msg > imu_msgPtr;
typedef boost::shared_ptr< ::imu_driver::imu_msg const> imu_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_driver::imu_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_driver::imu_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imu_driver::imu_msg_<ContainerAllocator1> & lhs, const ::imu_driver::imu_msg_<ContainerAllocator2> & rhs)
{
  return lhs.Header == rhs.Header &&
    lhs.Latitude == rhs.Latitude &&
    lhs.Longitude == rhs.Longitude &&
    lhs.Altitude == rhs.Altitude &&
    lhs.HDOP == rhs.HDOP &&
    lhs.UTM_easting == rhs.UTM_easting &&
    lhs.UTM_northing == rhs.UTM_northing &&
    lhs.UTC == rhs.UTC &&
    lhs.Zone == rhs.Zone &&
    lhs.Letter == rhs.Letter;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imu_driver::imu_msg_<ContainerAllocator1> & lhs, const ::imu_driver::imu_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imu_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::imu_driver::imu_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_driver::imu_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_driver::imu_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_driver::imu_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_driver::imu_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_driver::imu_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_driver::imu_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "66b6da1d45662ada473059e6ceda61cd";
  }

  static const char* value(const ::imu_driver::imu_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x66b6da1d45662adaULL;
  static const uint64_t static_value2 = 0x473059e6ceda61cdULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_driver::imu_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_driver/imu_msg";
  }

  static const char* value(const ::imu_driver::imu_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_driver::imu_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header Header\n"
"float64 Latitude\n"
"float64 Longitude\n"
"float64 Altitude\n"
"float64 HDOP\n"
"float64 UTM_easting\n"
"float64 UTM_northing\n"
"float64 UTC\n"
"int64 Zone\n"
"string Letter\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::imu_driver::imu_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_driver::imu_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Header);
      stream.next(m.Latitude);
      stream.next(m.Longitude);
      stream.next(m.Altitude);
      stream.next(m.HDOP);
      stream.next(m.UTM_easting);
      stream.next(m.UTM_northing);
      stream.next(m.UTC);
      stream.next(m.Zone);
      stream.next(m.Letter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imu_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_driver::imu_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_driver::imu_msg_<ContainerAllocator>& v)
  {
    s << indent << "Header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.Header);
    s << indent << "Latitude: ";
    Printer<double>::stream(s, indent + "  ", v.Latitude);
    s << indent << "Longitude: ";
    Printer<double>::stream(s, indent + "  ", v.Longitude);
    s << indent << "Altitude: ";
    Printer<double>::stream(s, indent + "  ", v.Altitude);
    s << indent << "HDOP: ";
    Printer<double>::stream(s, indent + "  ", v.HDOP);
    s << indent << "UTM_easting: ";
    Printer<double>::stream(s, indent + "  ", v.UTM_easting);
    s << indent << "UTM_northing: ";
    Printer<double>::stream(s, indent + "  ", v.UTM_northing);
    s << indent << "UTC: ";
    Printer<double>::stream(s, indent + "  ", v.UTC);
    s << indent << "Zone: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Zone);
    s << indent << "Letter: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Letter);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_DRIVER_MESSAGE_IMU_MSG_H
