bag1 = rosbag('C:\Users\Vinesh\Desktop\GroupData.bag');
bagselect1 = select(bag1,'topic','/imu');
msgstruct1 = readMessages(bagselect1,'DataFormat','struct');
msgstruct1{1}.Imu.AngularVelocity.X;
msgstruct1{1}.Imu.AngularVelocity.Y;
msgstruct1{1}.Imu.AngularVelocity.Z;
msgstruct1{1}.Header.Stamp.Sec;
gyroX = cellfun(@(m)double(m.Imu.AngularVelocity.X),msgstruct1);
gyroY = cellfun(@(m)double(m.Imu.AngularVelocity.Y),msgstruct1);
gyroZ = cellfun(@(m)double(m.Imu.AngularVelocity.Z),msgstruct1);
time = cellfun(@(m)double(m.Header.Stamp.Sec),msgstruct1);
qt = [orienW,orienX,orienY,orienZ];
eulXYZ = quat2eul(qt, "XYZ");
eulXYZ = rad2deg(eulXYZ);
figure(1);
subplot(3,1,1);
plot(time, gyroX);
title ('Time series - Gyro');
ylabel('Gyro X (m/sec)');
subplot(3,1,2);
plot(time, gyroY);
ylabel('Gyro Y (m/sec)');
subplot(3,1,3);
plot(time, gyroZ);
ylabel('Gyro Z (m/sec)');
xlabel('Time (seconds)');